language: node_js

node_js:
  - node

before_script:
  - npm install -g codeclimate-test-reporter

script:
  - make lint
  - make test

after_script:
  - codeclimate-test-reporter < coverage/lcov.info